#pragma once

#define MAX_COLUMN 6

enum RecruitHeader
{
	REC_HEADER_BAP = 0,
	REC_HEADER_NAME,
	REC_HEADER_AGENTCODE,
	REC_HEADER_DATE,
	REC_HEADER_RANK,
	REC_HEADER_SPONSOR,
	REC_HEADER_SMD,
	REC_HEADER_ACCREDITATION,
	REC_HEADER_END
};

enum SaleHeader
{
	SALE_HEADER_BAP = 0,
	SALE_HEADER_PROVIDERCODE,
	SALE_HEADER_APPNUMBER,
	SALE_HEADER_PRODUCTCODE,
	SALE_HEADER_POLICYNUMBER,
	SALE_HEADER_POLICYSTATUS,
	SALE_HEADER_PLANHOLDER,
	SALE_HEADER_PLANNAME,
	SALE_HEADER_PLANAMOUNT,
	SALE_HEADER_INSTALLAMOUNT,
	SALE_HEADER_BUSINESSDATE,
	SALE_HEADER_AGENTCODE1,
	SALE_HEADER_AGENTNAME1,
	SALE_HEADER_AGENTCODE2,
	SALE_HEADER_AGENTNAME2,
	SALE_HEADER_BASESHOP,
	SALE_HEADER_HIERARCHY,
	SALE_HEADER_SMD,
	SALE_HEADER_END
};

typedef enum enumPromotionType
{
	MD = 0,
	SMD,
	EMD,
	GJ,
	CEO,
	EVC,
	SEVC,
	OFFICE,
	HMO,
	LIMITEDPIN
} ENUMPROMOTIONTYPE;


enum
{
	INDEX_NAME = 0,
	INDEX_CODE,
	INDEX_UPLINE,
	INDEX_RANK,
	INDEX_DATE,
	INDEX_CURRENTRANK
};

typedef struct tagSMDLEGCOUNTER
{
	CString csSMDName;
	double lfLegCount;
	int nBapCount;
} SMDLEGCOUNTER;

typedef struct
{
	CString csSMDName;
	double lfBaseshopCount;
	double lfFirstGenCount;
	int nBapCount;
}SALESPOINTCOUNTER;

#define ENZO_COLOR_NAVYBLUE		RGB(260, 35, 126)
#define ENZO_COLOR_DIRTYWHITE	RGB(220, 220, 220)
#define ENZO_COLOR_WHITE		RGB(255,255,255)
#define ENZO_COLOR_BLACK		RGB(0,0,0)
#define ENZO_COLOR_GRAY			RGB(128,128,128)
#define ENZO_COLOR_YELLOW		RGB(255, 255, 0)
#define ENZO_COLOR_DARKGRAY     RGB(150, 150, 150)
